ecommerce/apps/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_summary, name="cart_summary"),
    path("add/", views.cart_add, name="cart_add"),
    path("delete/", views.cart_delete, name="cart_delete"),
    path("update/", views.cart_update, name="cart_update"),
]

ecommerce/apps/checkout/urls.py
from django.urls import include, path

from . import views

app_name = "checkout"

urlpatterns = [
    path("deliverychoices", views.deliverychoices, name="deliverychoices"),
    path(
        "cart_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"
    ),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ecommerce.apps.catalogue.urls", namespace="catalogue")),
    path("checkout/", include("ecommerce.apps.checkout.urls", namespace="checkout")),
    path("cart/", include("ecommerce.apps.cart.urls", namespace="cart")),
    path("account/", include("ecommerce.apps.account.urls", namespace="account")),
    path("orders/", include("ecommerce.apps.orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

ecommerce/apps/cart/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from ecommerce.apps.catalogue.models import Product

from .cart import Cart


def cart_summary(request):
    cart = Cart(request)
    return render(request, "cart/summary.html", {"cart": cart})


def cart_add(request):
    cart = Cart(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        product_qty = int(request.POST.get("productqty"))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)

        cartqty = cart.__len__()
        response = JsonResponse({"qty": cartqty})
        return response


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        cart.delete(product=product_id)

        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        response = JsonResponse({"qty": cartqty, "subtotal": carttotal})
        return response


def cart_update(request):
    cart = Cart(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        product_qty = int(request.POST.get("productqty"))
        cart.update(product=product_id, qty=product_qty)

        cartqty = cart.__len__()
        cartsubtotal = cart.get_subtotal_price()
        response = JsonResponse({"qty": cartqty, "subtotal": cartsubtotal})
        return response

templates/cart/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Cart Summary{% endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Your Cart</h1>
  </div>
  <div class="col-12">
    <p>Manage your <b>items</b> in your cart</p>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row g-3">
    {% if cart|length == 0 %}
    <div class="col-12">Your cart is empty <a href="{% url 'catalogue:store_home' %}">Shop</a></div>
    {% else %}
    <div class="col-12 bg-light p-3 d-flex justify-content-between">
      <div class="d-flex align-items-center">
        <div class="pe-3">Order</div>
        <div class="dropdown">
          <a class="text-decoration-none dropdown-toggle" href="#" role="button" id="shippingDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-truck me-2"></i> Shipping options
          </a>
          <ul class="dropdown-menu" aria-labelledby="shippingDropdown">
            <li><a class="dropdown-item shipping-option" href="#" data-option="next_day"><i class="bi bi-clock-history me-2"></i> Next day delivery <span class="fw-bold"></span></a></li>
            <li><a class="dropdown-item shipping-option" href="#" data-option="premium"><i class="bi bi-gem me-2"></i> Premium delivery <span class="fw-bold"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="text-end">
        <div class="">Sub Total: <span class="fw-bold">$ </span>
          <div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}}</div>
        </div>
        <div id="selected-shipping-option">Shipping <span class="small">( Select your shipping options )</span>: <span id="shipping-cost" class="fw-bold">$ 0.00</span></div>
        <div class="pt-2">Total to pay: <span class="fw-bold h5">$ </span><span id="total" class="fw-bold h5">{{cart.get_total_price}}</span></div>
      </div>
    </div>
    <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
      <div class="d-grid gap-2 ">
        <a role="button" href="{% url 'checkout:deliverychoices' %}" class="btn btn-success fw-bold" type="button">Checkout Securely</a>
        <button class="btn btn-light" type="button">Save for later</button>
      </div>
    </div>
    <div class="col-md-7 col-lg-8 p-0">
      {% for item in cart %}
      {% with product=item.product %}
      <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
        <div class="row g-0">
          <div class="col-md-2 d-none d-md-block">
            {% for image in product.product_image.all %}
            {% if image.is_feature%}
            <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
            {% endif %}
            {% endfor %}
          </div>
          <div class="col-md-10 ps-md-3">
            <div class="card-body p-1">
              <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                <p class="card-text pb-3">{{product.title}}</p>
              </a>

              
             <div class="d-flex align-items-center w-50 mt-2">
  <label for="quantity" class="me-2">Qty:</label>
  <div class="input-group me-2">
    <button class="btn btn-outline-secondary" type="button" id="minus-btn{{product.id}}">-</button>
    <input type="text" class="form-control store-select-dropdown" id="quantity{{product.id}}" value="{{ item.qty }}" readonly>
    <button class="btn btn-outline-secondary" type="button" id="plus-btn{{product.id}}">+</button>
  </div>
  <a role="button" id="update-button" data-index="{{product.id}}" class="update-button text-decoration-none btn btn-primary btn-sm me-2">Update</a>
  <a role="button" id="delete-button" data-index="{{product.id}}" class="delete-button text-decoration-none btn btn-danger btn-sm">Delete</a>
</div>



              
            </div>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>

<script>
  $(document).ready(function() {
    {% for item in cart %}
    var productId = "{{ item.product.id }}";
    $('#plus-btn{{ productId }}').click(function() {
      var value = parseInt($('#quantity{{ productId }}').val());
      $('#quantity{{ productId }}').val(value + 1);
    });

    $('#minus-btn{{ productId }}').click(function() {
      var value = parseInt($('#quantity{{ productId }}').val());
      if (value > 1) {
        $('#quantity{{ productId }}').val(value - 1);
      }
    });
    {% endfor %}

    $(document).on("click", ".shipping-option", function(e) {
      e.preventDefault();
      var shippingOptionName = $(this).text();
      document.getElementById("selected-shipping-option").innerHTML = "Shipping <span class='small'>" + shippingOptionName + "</span>: <span id='shipping-cost' class='fw-bold'>$ 3.00</span>";
      var shippingOption = $(this).data("option");
      var shippingCost = 0;
      if (shippingOption === "next_day") {
        shippingCost = 3;
      } else if (shippingOption === "premium") {
        shippingCost = 5;
      }
      document.getElementById("shipping-cost").innerHTML = "$ " + shippingCost.toFixed(2);
      var subtotal = parseFloat(document.getElementById("subtotal").innerText);
      var total = (subtotal + shippingCost).toFixed(2);
      document.getElementById("total").innerHTML = +total;
    });

    $(document).on("click", ".delete-button", function(e) {
      e.preventDefault();
      var prodid = $(this).data("index");
      $.ajax({
        type: "POST",
        url: '{% url "cart:cart_delete" %}',
        data: {
          productid: $(this).data("index"),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: "post",
        },
        success: function(json) {
          $('.product-item[data-index="' + prodid + '"]').remove();
          if (json.qty == 0) {
            total = 0
            subtotal = 0
          } else {
            total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
            subtotal = json.subtotal
          }
          document.getElementById("subtotal").innerHTML = subtotal;
          document.getElementById("cart-qty").innerHTML = json.qty;
          document.getElementById("total").innerHTML = total;
        },
        error: function(xhr, errmsg, err) {},
      });
    });

    $(document).on("click", ".update-button", function(e) {
      e.preventDefault();
      var prodid = $(this).data("index");
      $.ajax({
        type: "POST",
        url: '{% url "cart:cart_update" %}',
        data: {
          productid: $(this).data("index"),
          productqty: $("#quantity" + prodid + " option:selected").text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: "post",
        },
        success: function(json) {
          total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
          document.getElementById("cart-qty").innerHTML = json.qty;
          document.getElementById("subtotal").innerHTML = json.subtotal;
          document.getElementById("total").innerHTML = total;
        },
        error: function(xhr, errmsg, err) {},
      });
    });
  });
</script>


{% endblock %}